---
#
# Ansible managed
#
repository:
  description: Manage firewall ports on all (known) Linux operating systems.
  homepage: https://buluma.github.io/
  topics: firewall, firewalld, server, system, security, ansible, molecule, tox, playbook
